pipeline{
	agent any
		stages{
			stage ('Subindo docker compose'){
				steps{
					sh 'docker-compose up -d --scale chrome=4 --scale firefox=0'
					}
			}
			stage ('Build projeto'){
				steps{
					sh "docker-compose down"
				}
			}
		}
	
}