pipeline{
	agent any
		stages{
			stage ('Subindo docker compose'){
				steps{
					sh 'docker-compose up -d --scale chrome=4 --scale firefox=0'
					}
			}
			stage ('Build projeto'){
				steps{
					sh 'mvn clean package -DskipTests'
					dir ('/target')
					sh 'java -cp testcomseleniumjunit.jar:testcomseleniumjunit-tests.jar:target/libs/* org.testng.TesNG /src/test/resources/loginttest.xml'
				}
			}
		}
	
}