pipeline{
	agent any
		stages{
			stage ('Subindo docker compose'){
				steps{
					sh "docker-compose up"
					}
			}
			stage ('Build projeto'){
				steps{
					sh "docker-compose down"
				}
			}
		}
	
}